const types = {
    SET_PROCESS: "SET_PROCESS",
    ADD_ALL_PRODUCTS: "ADD_ALL_PRODUCTS",
    ADD_PRODUCT_TO_CART: "ADD_PRODUCT_TO_CART",
    REMOVE_PRODUCT_FORM_CART: "REMOVE_PRODUCT_FORM_CART",
    CLEANING_CART: "CLEANING_CART",
    CLEANING_CART_ITEM: "CLEANING_CART_ITEM"
};

export default types;
